{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | default .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  {{- if or .Values.host.exact .Values.host.prefixes }}
  hostnames:
    {{- range .Values.host.exact }}
    - {{ . | quote }}
    {{- end }}
    {{- range .Values.host.prefixes }}
    - {{ printf "%s.%s" . $.Values.host.domain | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /.well-known/openid-configuration
      backendRefs:
        - name: {{ .Chart.Name }}
          port: 80
    - matches:
        - path:
            type: Exact
            value: /openid/v1/jwks
      backendRefs:
        - name: {{ .Chart.Name }}
          port: 80
{{- end }}