# Source: oidc-discovery-proxy/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: oidc-discovery-proxy
  namespace: shared
  labels:
    app.kubernetes.io/name: oidc-discovery-proxy
    app.kubernetes.io/instance: oidc-discovery-proxy
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/managed-by: Helm
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oidc-discovery-proxy
      app.kubernetes.io/instance: oidc-discovery-proxy
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic from Envoy Gateway
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: shared
          podSelector:
            matchLabels:
              gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
              gateway.envoyproxy.io/owning-gateway-namespace: shared
      ports:
        - protocol: TCP
          port: 8080